site_name: Hello PHP !
theme:
  name: material
  feature:
    tabs: true
markdown_extensions:
    - fontawesome_markdown
    - admonition
    - codehilite:
        linenums: true
        use_pygments: true
        noclasses: true
        pygments_style: monokai
extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "css/custom.css"
    - "https://use.fontawesome.com/releases/v5.6.3/css/all.css"
extra:
    font:
        text: "Noto Sans JP"
        code: "Consolas"

